name: Compilar APK Policial

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar código
        uses: actions/checkout@v3

      - name: 2. Preparar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 3. Instalar librerías (Flet 0.22.1)
        run: |
          pip install -r requirements.txt

      - name: 4. Preparar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'

      - name: 5. Construir APK
        run: |
          flet build apk --verbose

      - name: 6. Subir el APK a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: App-Policial-APK
          path: build/app/outputs/apk/release/app-release.apk
